import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Find Event</title>
        <meta name="description" content="Generated by Find Event" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className="text-red-600 text-2xl font-bold">Test</p>
      </main>
    </div>
  );
}
